-- TripSense database schema
--
-- This file is DOCUMENTATION, not a migration script. Nothing runs it.
-- The real schema is generated by Hibernate from the @Entity classes in
-- src/main/java/csd/tripsense/ when the application starts.
--
-- Keep it in step: if a pull request adds or changes an entity, it updates
-- this file in the same commit. A schema file that has drifted from the code
-- is worse than no schema file at all.
--
-- To see the schema the database actually has:
--     sqlite3 data/tripsense.db ".schema"

-- News table for transit disruption updates and news articles.
-- Corresponds to the News entity in csd/tripsense/news/News.java
CREATE TABLE IF NOT EXISTS news (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    source TEXT,
    url TEXT,
    published_at TIMESTAMP
);

