-- TripSense database schema
--
-- This file is DOCUMENTATION, not a migration script. Nothing runs it.
-- The real schema is generated by Hibernate from the @Entity classes in
-- src/main/java/csd/tripsense/ when the application starts.
--
-- Keep it in step: if a pull request adds or changes an entity, it updates
-- this file in the same commit. A schema file that has drifted from the code
-- is worse than no schema file at all.
--
-- To see the schema the database actually has:
--     sqlite3 data/tripsense.db ".schema"


create table user {
    id integer primary key,
    username varchar not null,
    email varchar not null, 
    password varchar not null, 
    role varchar not null
}

create table country {
    id integer primary key,
    name varchar not null
}

create table itinerary {
    id integer primary key,
    user_id integer not null,
    country_id integer not null,
    name varchar,
    date_start timestamp,
    date_end timestamp,

    foreign key (user_id) references user(id),
    foreign key (country_id) references country(id)
}


create table activity {
    id integer primary key,
    itinerary_id integer not null,
    name varchar not null,
    address varchar,
    date_start timestamp,
    date_end timestamp,

    foreign key (itinerary_id) references itinerary(id)
}

-- News table for transit disruption updates and news articles.
-- Corresponds to the News entity in csd/tripsense/news/News.java
CREATE TABLE IF NOT EXISTS news (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    source TEXT,
    url TEXT,
    published_at TIMESTAMP
);

create table impact {
    id integer primary key,
    user_id integer not null,
    news_id integer not null,
    itinerary_id integer,
    activity_id integer,
    impacted boolean,
    reason varchar(500),

    foreign key (user_id) references user(id),
    foreign key (news_id) references news(id),
    foreign key (itinerary_id) references itinerary(id),
    foreign key (activity_id) references activity(id)
}
